### ISSUE TITLE
Unique service resource duplicated when module re-used.

### ISSUE THREAD

**Issue by jefffroman** [clarity-st/terraform-provider-clarity#4]
In the `service` resource, `unique = true` does not force services of the same `name` to be recognized as identical, and multiple services of the same name are created when the module is re-used with different parameters (but the same service name).

Example code:
**clarity_lambda.tf**
```
terraform {
  required_providers {
    clarity = {
      source    = "clarity-st/clarity"
      version   = "~> 0.0.3"
    }
  }
}

resource "clarity_service" "release_pipeline" {
  provider_slug = "my-repository"
  name          = var.name
  unique        = true
}

resource "clarity_resource" "release_target" {
  name          = var.env
  provider_slug = var.env
  service_slug  = clarity_service.release_pipeline.slug

  lambda {
    function_name = aws_lambda_function.lambda.function_name
    alias         = var.release_target
  }

  deployment {
    trigger {
      manual_user_interface = !(var.env == "dev")
    }
  }
}
```
**my-lambda.tf**
```
module "my-lambda" {
  source = "../../lib/clarity_lambda"
  env = "dev"
  name = "my-lambda"
  release_target = "clarity"
}

module "my-lambda" {
  source = "../../lib/clarity_lambda"
  env = "staging"
  name = "my-lambda"
  release_target = "clarity"
}
```
**Result**: This creates two different services in Clarity.
**Expectation**: One service is created, with two deployment targets.

**Comment by jefffroman** [comment]
Upon discussion, this seems to reflect a desire to have different terraform resource addresses referencing the same remote object, which doesn't produce deterministic behavior in Terraform.

This leaves the question of whether or not it's possible to leverage Clarity's structure of multiple targets per service when using Terraform, assuming each target represents a different deployment environment. Typically in Terraform code, the deployment environment is a high-level variable passed to each module.

**Comment by nhibberd** [comment]
Depends on the exact terraform structure you want to achieve. With an existing structure that is replicated around an "environment" module, I've outlined a couple of potential solutions below.

- A module defining an environment parameterized by the `env` name
```terraform
resource "aws_lambda_function" "${env}-my-lambda" { ... }

resource "aws_lambda_function" "${env}-my-other-lambda" { ... }
```

- Environments
```terraform
module "development" {
  source = "../environment"
  env    = "dev"
}

module "staging" {
  source = "../environment"
  env    = "staging"
}
```

# Option One - A central services module

- A module defining the `global` components, in this case the Clarity Services.
```terraform
# clarity provider
resource "clarity_provider" "repository" { ... }

# clarity services
resource "clarity_service" "api" {
  provider_slug = clarity_provider.repository.slug
  name          = "api"
  unique        = true
}

output "slugs" {
  description = "A set of clarity service slugs"
  value = {
    api = clarity_service.api.slug
    ...
  }
}
```
- An environment module
```terraform
resource "aws_iam_role" "role" { ... }

resource "aws_lambda_function" "function" { ... }
```

- The main module
```terraform
module "global" {
  source = "../services"
}

module "development" {
  source          = "../environment"
  env             = "dev"
  clarity_servies = module.global.slugs
}

module "staging" {
  source          = "../environment"
  env             = "staging"
  clarity_servies = module.global.slugs
}

module "prod" {
  source          = "../environment"
  env             = "prod"
  clarity_servies = module.global.slugs
}
```

# Option Two - terraform organized by service, not an environment

- A module defining a single service across multiple standard environments (dev, staging, prod)
```terraform
resource "aws_iam_role" "role" { ... }

resource "aws_lambda_function" "function" { ... }

resource "clarity_service" "service" { ... }

resource "clarity_resource" "devg" { ... }

resource "clarity_resource" "staging" { ... }

resource "clarity_resource" "prod" { ... }
```

- The main defintion
```terraform
# clarity provider
resource "clarity_provider" "repository" {
  ...
}

module "my-lambda" {
  source = "./lambda"
  name = "my-lambda"
  repository = clarity_provider.repository.slug
}

module "my-other-lambda" {
  source = "./lambda"
  name = "my-other-lambda"
  repository = clarity_provider.repository.slug
}
```

**Comment by jefffroman** [comment]
Good suggestions, thanks. I think both of these require that something be organized by service rather than environment -- either the entire configuration for a given lambda, or just the call to the global module for each lambda. I'm not sure either fits our architecture, which is organized by environment, and we'd rather not have to duplicate code for the global and environment-specific sections. Each lambda we have should be configured identically in each environment, for which it seems we'll need a separate service per environment for each lambda, each with a single target. That can certainly work, it's just seems a shameful misuse/underutilization of Clarity's nice service-target tree capabilities.

**Comment by jefffroman** [comment]
This fix along with an adjustment towards using the suggested architectures solves this issue as best it can be solved I think. Closing.
